<?php

namespace api\helpers\enum;

use common\modules\base\helpers\enum\BaseEnum;

class Error extends BaseEnum
{

	// General
	const ERROR_NONE								= 0;
	const ERROR_UNKNOWN								= 1;
	const ERROR_ACCESS_DENIED						= 2;
	const ERROR_EMPTY_PARAMS						= 100;
	const ERROR_INVALID_PARAMS						= 101;
	const ERROR_REGISTRATION_DISABLED				= 102;
	const ERROR_FORGOT_DISABLED						= 103;

	// User
	const ERROR_USER_FIELD_EMPTY_EMAIL				= 1000;
	const ERROR_USER_FIELD_EMPTY_USERNAME			= 1001;
	const ERROR_USER_FIELD_EMPTY_PASSWORD			= 1002;
	const ERROR_USER_FIELD_EMPTY_FIRST_NAME			= 1003;

	const ERROR_USER_FIELD_SHORT_USERNAME			= 1010;
	const ERROR_USER_FIELD_SHORT_PASSWORD			= 1011;
	const ERROR_USER_FIELD_SHORT_FIRST_NAME			= 1012;
	const ERROR_USER_FIELD_SHORT_LAST_NAME			= 1013;
	const ERROR_USER_FIELD_SHORT_MIDDLE_NAME		= 1014;

	const ERROR_USER_FIELD_LONG_USERNAME			= 1020;
	const ERROR_USER_FIELD_LONG_PASSWORD			= 1021;
	const ERROR_USER_FIELD_LONG_FIRST_NAME			= 1022;
	const ERROR_USER_FIELD_LONG_LAST_NAME			= 1023;
	const ERROR_USER_FIELD_LONG_MIDDLE_NAME			= 1024;

	const ERROR_USER_FIELD_INVALID_EMAIL			= 1030;
	const ERROR_USER_FIELD_INVALID_USERNAME			= 1031;
	const ERROR_USER_FIELD_INVALID_PASSWORD			= 1032;
	const ERROR_USER_FIELD_INVALID_PHONE			= 1033;

	const ERROR_USER_FIELD_EXISTS_EMAIL				= 1040;
	const ERROR_USER_FIELD_EXISTS_USERNAME			= 1041;

	const ERROR_USER_FIELD_NOT_EXISTS_EMAIL			= 1050;
	const ERROR_USER_FIELD_NOT_EXISTS_TOKEN			= 1052;

	const ERROR_USER_STATUS_UNCONFIRMED				= 1060;
	const ERROR_USER_STATUS_BLOCKED					= 1061;
	const ERROR_USER_STATUS_DELETED					= 1062;
    
    const ERROR_MAILING_USER_ACCESS                 = 2000;
    const ERROR_MAILING_USER_EMPTY_EMAIL            = 2001;
	const ERROR_MAILING_USER_EXISTS                 = 2002;
	
	/**
	 * @var string message category
	 */
	public static $messageCategory = 'api-error';

	/**
	 * @var array list of properties
	 */
	public static $list = [
		self::ERROR_NONE 							=> 'ERROR_NONE',
		self::ERROR_UNKNOWN							=> 'ERROR_UNKNOWN',
		self::ERROR_ACCESS_DENIED					=> 'ERROR_ACCESS_DENIED',
		self::ERROR_EMPTY_PARAMS					=> 'ERROR_EMPTY_PARAMS',
		self::ERROR_INVALID_PARAMS					=> 'ERROR_INVALID_PARAMS',
		self::ERROR_REGISTRATION_DISABLED			=> 'ERROR_REGISTRATION_DISABLED',
		self::ERROR_FORGOT_DISABLED					=> 'ERROR_FORGOT_DISABLED',

		self::ERROR_USER_FIELD_EMPTY_EMAIL			=> 'ERROR_USER_FIELD_EMPTY_EMAIL',
		self::ERROR_USER_FIELD_EMPTY_USERNAME 		=> 'ERROR_USER_FIELD_EMPTY_USERNAME',
		self::ERROR_USER_FIELD_EMPTY_PASSWORD		=> 'ERROR_USER_FIELD_EMPTY_PASSWORD',
		self::ERROR_USER_FIELD_EMPTY_FIRST_NAME		=> 'ERROR_USER_FIELD_EMPTY_FIRST_NAME',

		self::ERROR_USER_FIELD_SHORT_USERNAME		=> 'ERROR_USER_FIELD_SHORT_USERNAME',
		self::ERROR_USER_FIELD_SHORT_PASSWORD		=> 'ERROR_USER_FIELD_SHORT_PASSWORD',
		self::ERROR_USER_FIELD_SHORT_FIRST_NAME		=> 'ERROR_USER_FIELD_SHORT_FIRST_NAME',
		self::ERROR_USER_FIELD_SHORT_LAST_NAME		=> 'ERROR_USER_FIELD_SHORT_LAST_NAME',
		self::ERROR_USER_FIELD_SHORT_MIDDLE_NAME	=> 'ERROR_USER_FIELD_SHORT_MIDDLE_NAME',

		self::ERROR_USER_FIELD_LONG_USERNAME		=> 'ERROR_USER_FIELD_LONG_USERNAME',
		self::ERROR_USER_FIELD_LONG_PASSWORD		=> 'ERROR_USER_FIELD_LONG_PASSWORD',
		self::ERROR_USER_FIELD_LONG_FIRST_NAME		=> 'ERROR_USER_FIELD_LONG_FIRST_NAME',
		self::ERROR_USER_FIELD_LONG_LAST_NAME		=> 'ERROR_USER_FIELD_LONG_LAST_NAME',
		self::ERROR_USER_FIELD_LONG_MIDDLE_NAME		=> 'ERROR_USER_FIELD_LONG_MIDDLE_NAME',

		self::ERROR_USER_FIELD_INVALID_EMAIL		=> 'ERROR_USER_FIELD_INVALID_EMAIL',
		self::ERROR_USER_FIELD_INVALID_USERNAME		=> 'ERROR_USER_FIELD_INVALID_USERNAME',
		self::ERROR_USER_FIELD_INVALID_PASSWORD		=> 'ERROR_USER_FIELD_INVALID_PASSWORD',
		self::ERROR_USER_FIELD_INVALID_PHONE		=> 'ERROR_USER_FIELD_INVALID_PHONE',

		self::ERROR_USER_FIELD_EXISTS_EMAIL			=> 'ERROR_USER_FIELD_EXISTS_EMAIL',
		self::ERROR_USER_FIELD_EXISTS_USERNAME		=> 'ERROR_USER_FIELD_EXISTS_USERNAME',

		self::ERROR_USER_FIELD_NOT_EXISTS_EMAIL		=> 'ERROR_USER_FIELD_NOT_EXISTS_EMAIL',
		self::ERROR_USER_FIELD_NOT_EXISTS_TOKEN		=> 'ERROR_USER_FIELD_NOT_EXISTS_TOKEN',

		self::ERROR_USER_STATUS_UNCONFIRMED			=> 'ERROR_USER_STATUS_UNCONFIRMED',
		self::ERROR_USER_STATUS_BLOCKED				=> 'ERROR_USER_STATUS_BLOCKED',
		self::ERROR_USER_STATUS_DELETED				=> 'ERROR_USER_STATUS_DELETED',
        
        self::ERROR_MAILING_USER_ACCESS             => 'ERROR_MAILING_USER_ACCESS',
        self::ERROR_MAILING_USER_EMPTY_EMAIL        => 'ERROR_MAILING_USER_EMPTY_EMAIL',
        self::ERROR_MAILING_USER_EXISTS             => 'ERROR_MAILING_USER_EXISTS'
	];

	/**
	 * @var array list of exclude
	 */
	public static $exclude = [];
}